template = "https://github.com/giellalt/template-lang-und"
rev_id = 328
template_sha = "a66ce6606ea33e46cd3439c88cafa44d4dcdde92"

[replacements]
__GLOTTOLOG_ID__ = "telu1262"
__REPO__ = "lang-tel"
__UND2C__ = "te"
__UNDEFINED__ = "Telugu"
__UND__ = "tel"
