template = "https://github.com/giellalt/template-lang-und"
rev_id = 335
template_sha = "656172fb5ca68a68ee8547c7bc0cd1ce3f605fd7"

[replacements]
__GLOTTOLOG_ID__ = "telu1262"
__REPO__ = "lang-tel"
__UND2C__ = "te"
__UNDEFINED__ = "Telugu"
__UND__ = "tel"
