template = "https://github.com/giellalt/template-lang-und"
rev_id = 317
template_sha = "3d0bcfa8020a96bc946192565f7e92213470a110"

[replacements]
__GLOTTOLOG_ID__ = "telu1262"
__REPO__ = "lang-tel"
__UND2C__ = "te"
__UNDEFINED__ = "Telugu"
__UND__ = "tel"
