[package]
name = "tel"
human_name = "Telugu"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.tel]
filename = "te-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-tel"
platform = "windows"
uuid = "F61A1BA6-B72F-4516-B574-23C887EE339E"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.te"
package = "speller-tel"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-tel-mso"
platform = "windows"
uuid = "7B2F82D6-64F2-49B3-AFB2-859D7F6E0ACC"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-tel"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
